<?php 
session_start();

// AUTH CHECK
if (!isset($_SESSION['logged_in'])) {
    header("Location: ../../login.php");
    exit();
}
if (strtolower($_SESSION['role_name']) !== 'production') {
    header("Location: ../../login.php");
    exit();
}

$nav = "./";
$link = "../include/";
include($link."container/head.php");
include($link."container/nav.php");
require($link . "php/config.php");
require_once($link . "php/productionManager/production_functions.php");

// Get all data
$total_value = getTotalStockValue($conn);
$total_quantity = getTotalStockQuantity($conn);
$total_products = getTotalProducts($conn);
$total_area = getTotalStockArea($conn);
$low_stock = getLowStockProducts($conn);
$stock_by_category = getStockByCategory($conn);
$all_products = getAllProductsForProduction($conn);
?>

<style>
.report-container {
    max-width: 1200px;
    margin: 20px auto;
    background: white;
    padding: 40px;
}

.report-header {
    text-align: center;
    border-bottom: 3px solid #007bff;
    padding-bottom: 20px;
    margin-bottom: 30px;
}

.report-header h1 {
    margin: 0;
    color: #333;
}

.report-info {
    display: flex;
    justify-content: space-between;
    margin: 20px 0;
    padding: 15px;
    background: #f8f9fa;
    border-radius: 5px;
}

.summary-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 15px;
    margin: 30px 0;
}

.summary-box {
    background: #f8f9fa;
    padding: 20px;
    border-radius: 8px;
    text-align: center;
    border: 2px solid #dee2e6;
}

.summary-box .value {
    font-size: 28px;
    font-weight: bold;
    color: #007bff;
    margin: 10px 0;
}

.summary-box .label {
    color: #666;
    font-size: 14px;
}

.report-section {
    margin: 40px 0;
}

.report-section h2 {
    color: #007bff;
    border-bottom: 2px solid #dee2e6;
    padding-bottom: 10px;
    margin-bottom: 20px;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
}

table th, table td {
    padding: 12px;
    text-align: left;
    border: 1px solid #dee2e6;
}

table thead {
    background: #007bff;
    color: white;
}

table tbody tr:nth-child(even) {
    background: #f8f9fa;
}

table tbody tr:hover {
    background: #e9ecef;
}

.btn {
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-size: 14px;
    text-decoration: none;
    display: inline-block;
    margin-right: 10px;
}

.btn-primary {
    background: #007bff;
    color: white;
}

.btn-secondary {
    background: #6c757d;
    color: white;
}

@media print {
    .btn, nav, .no-print {
        display: none !important;
    }
    .report-container {
        padding: 20px;
    }
    table {
        font-size: 12px;
    }
    .summary-grid {
        grid-template-columns: repeat(4, 1fr);
        page-break-inside: avoid;
    }
}
</style>

<div class="main">
    <div class="no-print" style="margin: 20px 0;">
        <button class="btn btn-secondary" onclick="window.location.href='./index.php'">
            Back to Dashboard
        </button>
        <button class="btn btn-primary" onclick="printTable()">
            Print Report
        </button>
        <button class="btn btn-primary" onclick="exportToCSV()">
            Export to CSV
        </button>
    </div>
    
    <div class="report-container"  id="printTable">
        <!-- Report Header -->
        <div class="report-header">
            <h1>STOCK REPORT</h1>
            <p style="margin: 10px 0 0 0; color: #666;">Production Manager View Only Report</p>
        </div>
        
        <!-- Report Info -->
        <div class="report-info">
            <div>
                <strong>Report Date:</strong> <?= date('d/m/Y'); ?>
            </div>
            <div>
                <strong>Time:</strong> <?= date('H:i:s'); ?>
            </div>
            <div>
                <strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['username']); ?>
            </div>
        </div>
        
        <!-- Summary Section -->
        <div class="summary-grid" >
            <div class="summary-box">
                <div class="label">Total Stock Value</div>
                <div class="value">RM <?= number_format($total_value, 2); ?></div>
            </div>
            <div class="summary-box">
                <div class="label">Total Stock Items</div>
                <div class="value"><?= number_format($total_products); ?></div>
            </div>
            <div class="summary-box">
                <div class="label">Total Quantity</div>
                <div class="value"><?= number_format($total_quantity, 2); ?></div>
            </div>
            <div class="summary-box">
                <div class="label">Total Area (m²)</div>
                <div class="value"><?= number_format($total_area, 2); ?></div>
            </div>
        </div>
        
        <div class="summary-grid" style="grid-template-columns: repeat(2, 1fr);">
            <div class="summary-box">
                <div class="label">Low Stock Items</div>
                <div class="value" style="color: <?= $low_stock > 0 ? '#dc3545' : '#28a745' ?>;">
                    <?= $low_stock; ?>
                </div>
            </div>
            <div class="summary-box">
                <div class="label">Average Cost/m²</div>
                <div class="value">
                    RM <?= $total_area > 0 ? number_format($total_value / $total_area, 2) : '0.00'; ?>
                </div>
            </div>
        </div>
        
        <!-- Stock by Type -->
        <div class="report-section">
            <h2>Stock Summary by Type</h2>
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Items</th>
                        <th>Total Quantity</th>
                        <th>Total Area (m²)</th>
                        <th>Total Value (RM)</th>
                        <th>Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $stock_by_category->data_seek(0); // Reset pointer
                    while ($cat = $stock_by_category->fetch_assoc()): 
                        $percentage = $total_value > 0 ? (($cat['type_value'] ?? 0) / $total_value * 100) : 0;
                    ?>
                        <tr>
                            <td><?= htmlspecialchars($cat['type_name'] ?? 'Unknown'); ?></td>
                            <td><?= $cat['item_count']; ?></td>
                            <td><?= number_format($cat['total_quantity'] ?? 0, 2); ?></td>
                            <td><?= number_format($cat['total_area'] ?? 0, 2); ?></td>
                            <td>RM <?= number_format($cat['type_value'] ?? 0, 2); ?></td>
                            <td><?= number_format($percentage, 1); ?>%</td>
                        </tr>
                    <?php endwhile; ?>
                </tbody>
            </table>
        </div>
        
        <!-- All Products Detail -->
        <div class="report-section">
            <h2>Complete Stock List</h2>
            <table>
                <thead>
                    <tr>
                        <th>Stock ID</th>
                        <th>Description</th>
                        <th>Type</th>
                        <th>Dimensions (L×W)</th>
                        <th>Quantity</th>
                        <th>Total Area (m²)</th>
                        <th>Cost/m²</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $all_products->data_seek(0); // Reset pointer
                    $grand_total = 0;
                    while ($row = $all_products->fetch_assoc()): 
                        $grand_total += $row['total_amount'];
                        $stock_status = '';
                        if($row['quantity'] <= 5) {
                            $stock_status = 'Critical';
                        } elseif($row['quantity'] <= 10) {
                            $stock_status = 'Low Stock';
                        } else {
                            $stock_status = 'Available';
                        }
                    ?>
                        <tr>
                            <td><?= htmlspecialchars($row['stock_id']); ?></td>
                            <td><?= htmlspecialchars($row['description']); ?></td>
                            <td><?= htmlspecialchars($row['type_name'] ?? 'N/A'); ?></td>
                            <td><?= number_format($row['length'], 2); ?> × <?= number_format($row['width'], 2); ?></td>
                            <td><?= number_format($row['quantity'], 2); ?></td>
                            <td><?= number_format($row['total_area'], 2); ?></td>
                            <td>RM <?= number_format($row['cost_per_m2'], 2); ?></td>
                            <td>RM <?= number_format($row['total_amount'], 2); ?></td>
                            <td><?= $stock_status; ?></td>
                        </tr>
                    <?php endwhile; ?>
                    <tr style="background: #f0f0f0; font-weight: bold;">
                        <td colspan="7" style="text-align: right;">GRAND TOTAL:</td>
                        <td colspan="2">RM <?= number_format($grand_total, 2); ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <!-- Footer -->
        <div style="margin-top: 50px; padding-top: 20px; border-top: 2px solid #dee2e6; text-align: center; color: #666;">
            <p><strong>This is a system-generated report - View Only Access</strong></p>
            <p>For any stock adjustments or updates, please contact the Accountant department.</p>
            <p style="font-size: 12px; margin-top: 20px;">
                Report Generated: <?= date('d/m/Y H:i:s'); ?> | User: <?= htmlspecialchars($_SESSION['username']); ?>
            </p>
        </div>
    </div>
</div>

<script>
function exportToCSV() {
    const data = [];
    
    // Header
    data.push(['STOCK REPORT - ' + new Date().toLocaleDateString()]);
    data.push([]);
    data.push(['Stock ID', 'Description', 'Type', 'Dimensions (L×W)', 'Quantity', 'Total Area', 'Cost/m²', 'Total Amount', 'Status']);
    
    // Get table data from Complete Stock List table
    const tables = document.querySelectorAll('.report-section table');
    const stockTable = tables[1]; // Second table (Complete Stock List)
    const rows = stockTable.querySelectorAll('tbody tr');
    
    rows.forEach(row => {
        const cols = row.querySelectorAll('td');
        if (cols.length > 0 && !row.querySelector('td[colspan]')) {
            const rowData = Array.from(cols).map(col => col.textContent.trim().replace(/,/g, ''));
            data.push(rowData);
        }
    });
    
    // Convert to CSV
    let csv = data.map(row => row.join(',')).join('\n');
    
    // Download
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'stock_report_' + new Date().toISOString().split('T')[0] + '.csv';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
}

function printTable() {
  var table = document.getElementById("printTable").outerHTML;
  var win = window.open("", "", "width=900,height=700");

  win.document.write(`
    <html>
      <head>
        <title>Print</title>
        <style>
          table { width: 100%; border-collapse: collapse; }
          th, td { border: 1px solid #000; padding: 8px; }
          .report-container {
    max-width: 1200px;
    margin: 20px auto;
    background: white;
    padding: 40px;
}

.report-header {
    text-align: center;
    border-bottom: 3px solid #007bff;
    padding-bottom: 20px;
    margin-bottom: 30px;
}

.report-header h1 {
    margin: 0;
    color: #333;
}

.report-info {
    display: flex;
    justify-content: space-between;
    margin: 20px 0;
    padding: 15px;
    background: #f8f9fa;
    border-radius: 5px;
}

.summary-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 15px;
    margin: 30px 0;
}

.summary-box {
    background: #f8f9fa;
    padding: 20px;
    border-radius: 8px;
    text-align: center;
    border: 2px solid #dee2e6;
}

.summary-box .value {
    font-size: 28px;
    font-weight: bold;
    color: #007bff;
    margin: 10px 0;
}

.summary-box .label {
    color: #666;
    font-size: 14px;
}

.report-section {
    margin: 40px 0;
}

.report-section h2 {
    color: #007bff;
    border-bottom: 2px solid #dee2e6;
    padding-bottom: 10px;
    margin-bottom: 20px;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
}

table th, table td {
    padding: 12px;
    text-align: left;
    border: 1px solid #dee2e6;
}

table thead {
    background: #007bff;
    color: white;
}

table tbody tr:nth-child(even) {
    background: #f8f9fa;
}

table tbody tr:hover {
    background: #e9ecef;
}
        </style>
      </head>
      <body>
        ${table}
      </body>
    </html>
  `);

  win.document.close();
  win.print();
  win.close();
}
</script>

<?php 
include($link."container/footer.php");
?>